apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: '{{ metadata.annotations.gitRepo }}'
              revision: '{{ metadata.annotations.gitRevision }}'
              directories:
                - path: apps/*
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: '{{ metadata.annotations.gitRepo }}'
        targetRevision: '{{ metadata.annotations.gitRevision }}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ metadata.annotations.aapNamespace }}'
      syncPolicy:
        automated: {}
