apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: aap-argo
spec:
  generators:
    - git:
        revision: HEAD
        repoURL: https://github.com/roelandpol/aap-bootstrap.git
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/roelandpol/aap-bootstrap.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: aap

