apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: aap-argo
spec:
  generators:
    - matrix:
        generators:
          - git:
              revision: HEAD
              repoURL: https://github.com/roelandpol/aap-iac.git
              directories:
                - path: apps/*
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/roelandpol/aap-iac.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: aap
      syncPolicy:
        automated: {}
