apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: master
  namespace: aap-argo
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - clusters: {}
  template:
    metadata:
      name: master
    spec:
      project: default
      source:
        repoURL: '{{ metadata.annotations.gitRepo }}'
        targetRevision: HEAD
        path: appsets
        directory:
          include: '*.yaml'
      destination:
        namespace: '{{ metadata.annotations.argoNamespace }}'
